// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Activity {

	@TarsStructProperty(order = 0, isRequire = true)
	public int activityId = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public String title = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public String detail = "";
	@TarsStructProperty(order = 3, isRequire = true)
	public String coverURL = "";
	@TarsStructProperty(order = 4, isRequire = true)
	public long startTime = 0L;
	@TarsStructProperty(order = 5, isRequire = true)
	public long endTime = 0L;
	@TarsStructProperty(order = 6, isRequire = true)
	public String activityUrl = "";
	@TarsStructProperty(order = 7, isRequire = true)
	public String activityDataUrl = "";
	@TarsStructProperty(order = 8, isRequire = true)
	public String iconUrl = "";

	public int getActivityId() {
		return activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public String getCoverURL() {
		return coverURL;
	}

	public void setCoverURL(String coverURL) {
		this.coverURL = coverURL;
	}

	public long getStartTime() {
		return startTime;
	}

	public void setStartTime(long startTime) {
		this.startTime = startTime;
	}

	public long getEndTime() {
		return endTime;
	}

	public void setEndTime(long endTime) {
		this.endTime = endTime;
	}

	public String getActivityUrl() {
		return activityUrl;
	}

	public void setActivityUrl(String activityUrl) {
		this.activityUrl = activityUrl;
	}

	public String getActivityDataUrl() {
		return activityDataUrl;
	}

	public void setActivityDataUrl(String activityDataUrl) {
		this.activityDataUrl = activityDataUrl;
	}

	public String getIconUrl() {
		return iconUrl;
	}

	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}

	public Activity() {
	}

	public Activity(int activityId, String title, String detail, String coverURL, long startTime, long endTime, String activityUrl, String activityDataUrl, String iconUrl) {
		this.activityId = activityId;
		this.title = title;
		this.detail = detail;
		this.coverURL = coverURL;
		this.startTime = startTime;
		this.endTime = endTime;
		this.activityUrl = activityUrl;
		this.activityDataUrl = activityDataUrl;
		this.iconUrl = iconUrl;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(activityId);
		result = prime * result + TarsUtil.hashCode(title);
		result = prime * result + TarsUtil.hashCode(detail);
		result = prime * result + TarsUtil.hashCode(coverURL);
		result = prime * result + TarsUtil.hashCode(startTime);
		result = prime * result + TarsUtil.hashCode(endTime);
		result = prime * result + TarsUtil.hashCode(activityUrl);
		result = prime * result + TarsUtil.hashCode(activityDataUrl);
		result = prime * result + TarsUtil.hashCode(iconUrl);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Activity)) {
			return false;
		}
		Activity other = (Activity) obj;
		return (
			TarsUtil.equals(activityId, other.activityId) &&
			TarsUtil.equals(title, other.title) &&
			TarsUtil.equals(detail, other.detail) &&
			TarsUtil.equals(coverURL, other.coverURL) &&
			TarsUtil.equals(startTime, other.startTime) &&
			TarsUtil.equals(endTime, other.endTime) &&
			TarsUtil.equals(activityUrl, other.activityUrl) &&
			TarsUtil.equals(activityDataUrl, other.activityDataUrl) &&
			TarsUtil.equals(iconUrl, other.iconUrl) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(activityId, 0);
		_os.write(title, 1);
		_os.write(detail, 2);
		_os.write(coverURL, 3);
		_os.write(startTime, 4);
		_os.write(endTime, 5);
		_os.write(activityUrl, 6);
		_os.write(activityDataUrl, 7);
		_os.write(iconUrl, 8);
	}


	public void readFrom(TarsInputStream _is) {
		this.activityId = _is.read(activityId, 0, true);
		this.title = _is.readString(1, true);
		this.detail = _is.readString(2, true);
		this.coverURL = _is.readString(3, true);
		this.startTime = _is.read(startTime, 4, true);
		this.endTime = _is.read(endTime, 5, true);
		this.activityUrl = _is.readString(6, true);
		this.activityDataUrl = _is.readString(7, true);
		this.iconUrl = _is.readString(8, true);
	}

}
