// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class AppleIAPVerifyRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public String iapKey = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String iapReceipt = "";

	public String getIapKey() {
		return iapKey;
	}

	public void setIapKey(String iapKey) {
		this.iapKey = iapKey;
	}

	public String getIapReceipt() {
		return iapReceipt;
	}

	public void setIapReceipt(String iapReceipt) {
		this.iapReceipt = iapReceipt;
	}

	public AppleIAPVerifyRequest() {
	}

	public AppleIAPVerifyRequest(String iapKey, String iapReceipt) {
		this.iapKey = iapKey;
		this.iapReceipt = iapReceipt;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iapKey);
		result = prime * result + TarsUtil.hashCode(iapReceipt);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AppleIAPVerifyRequest)) {
			return false;
		}
		AppleIAPVerifyRequest other = (AppleIAPVerifyRequest) obj;
		return (
			TarsUtil.equals(iapKey, other.iapKey) &&
			TarsUtil.equals(iapReceipt, other.iapReceipt) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iapKey, 0);
		_os.write(iapReceipt, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.iapKey = _is.readString(0, true);
		this.iapReceipt = _is.readString(1, true);
	}

}
