// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class AppleIAPVerifyResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public String validResponse = "";

	public String getValidResponse() {
		return validResponse;
	}

	public void setValidResponse(String validResponse) {
		this.validResponse = validResponse;
	}

	public AppleIAPVerifyResponse() {
	}

	public AppleIAPVerifyResponse(String validResponse) {
		this.validResponse = validResponse;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(validResponse);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AppleIAPVerifyResponse)) {
			return false;
		}
		AppleIAPVerifyResponse other = (AppleIAPVerifyResponse) obj;
		return (
			TarsUtil.equals(validResponse, other.validResponse) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(validResponse, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.validResponse = _is.readString(0, true);
	}

}
