// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Banner {

	@TarsStructProperty(order = 0, isRequire = true)
	public String coverURL = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String url = "";

	public String getCoverURL() {
		return coverURL;
	}

	public void setCoverURL(String coverURL) {
		this.coverURL = coverURL;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Banner() {
	}

	public Banner(String coverURL, String url) {
		this.coverURL = coverURL;
		this.url = url;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(coverURL);
		result = prime * result + TarsUtil.hashCode(url);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Banner)) {
			return false;
		}
		Banner other = (Banner) obj;
		return (
			TarsUtil.equals(coverURL, other.coverURL) &&
			TarsUtil.equals(url, other.url) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(coverURL, 0);
		_os.write(url, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.coverURL = _is.readString(0, true);
		this.url = _is.readString(1, true);
	}

}
