// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class BookBase {

	@TarsStructProperty(order = 0, isRequire = true)
	public long bookID = 0L;
	@TarsStructProperty(order = 1, isRequire = true)
	public String name = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public String coverURL = "";
	@TarsStructProperty(order = 3, isRequire = true)
	public String fullName = "";

	public long getBookID() {
		return bookID;
	}

	public void setBookID(long bookID) {
		this.bookID = bookID;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCoverURL() {
		return coverURL;
	}

	public void setCoverURL(String coverURL) {
		this.coverURL = coverURL;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public BookBase() {
	}

	public BookBase(long bookID, String name, String coverURL, String fullName) {
		this.bookID = bookID;
		this.name = name;
		this.coverURL = coverURL;
		this.fullName = fullName;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(bookID);
		result = prime * result + TarsUtil.hashCode(name);
		result = prime * result + TarsUtil.hashCode(coverURL);
		result = prime * result + TarsUtil.hashCode(fullName);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof BookBase)) {
			return false;
		}
		BookBase other = (BookBase) obj;
		return (
			TarsUtil.equals(bookID, other.bookID) &&
			TarsUtil.equals(name, other.name) &&
			TarsUtil.equals(coverURL, other.coverURL) &&
			TarsUtil.equals(fullName, other.fullName) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(bookID, 0);
		_os.write(name, 1);
		_os.write(coverURL, 2);
		_os.write(fullName, 3);
	}


	public void readFrom(TarsInputStream _is) {
		this.bookID = _is.read(bookID, 0, true);
		this.name = _is.readString(1, true);
		this.coverURL = _is.readString(2, true);
		this.fullName = _is.readString(3, true);
	}

}
