// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

public interface DDBConst {

	public static final int OK = 0;

	public static final int ERR_DECODE = 1000000;

	public static final int ERR_PARAM = 1000010;

	public static final int ERR_PACKAGE = 1000020;

	public static final int ERR_FUNCNAME = 1000030;

	public static final int ERR_REDIS = 1000110;

	public static final int ERR_EXCEPTION = 1000100;

	public static final int ERR_SMS_LIMIT = 1001001;

	public static final int ERR_ONS_PRODUCE = 1000201;

	public static final int ERR_EXPIRE_VERIFYCODE = 3000001;

	public static final int ERR_WRONG_VERIFYCODE = 3000002;

	public static final int ERR_SERVER_INVOKE = 3000003;
}
