// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Dialogue {

	@TarsStructProperty(order = 0, isRequire = true)
	public String talker = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String content = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public String encryptSoundURL = "";

	public String getTalker() {
		return talker;
	}

	public void setTalker(String talker) {
		this.talker = talker;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getEncryptSoundURL() {
		return encryptSoundURL;
	}

	public void setEncryptSoundURL(String encryptSoundURL) {
		this.encryptSoundURL = encryptSoundURL;
	}

	public Dialogue() {
	}

	public Dialogue(String talker, String content, String encryptSoundURL) {
		this.talker = talker;
		this.content = content;
		this.encryptSoundURL = encryptSoundURL;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(talker);
		result = prime * result + TarsUtil.hashCode(content);
		result = prime * result + TarsUtil.hashCode(encryptSoundURL);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Dialogue)) {
			return false;
		}
		Dialogue other = (Dialogue) obj;
		return (
			TarsUtil.equals(talker, other.talker) &&
			TarsUtil.equals(content, other.content) &&
			TarsUtil.equals(encryptSoundURL, other.encryptSoundURL) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(talker, 0);
		_os.write(content, 1);
		_os.write(encryptSoundURL, 2);
	}


	public void readFrom(TarsInputStream _is) {
		this.talker = _is.readString(0, true);
		this.content = _is.readString(1, true);
		this.encryptSoundURL = _is.readString(2, true);
	}

}
