// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class District {

	@TarsStructProperty(order = 0, isRequire = true)
	public String name = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public int areaCode = 0;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(int areaCode) {
		this.areaCode = areaCode;
	}

	public District() {
	}

	public District(String name, int areaCode) {
		this.name = name;
		this.areaCode = areaCode;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(name);
		result = prime * result + TarsUtil.hashCode(areaCode);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof District)) {
			return false;
		}
		District other = (District) obj;
		return (
			TarsUtil.equals(name, other.name) &&
			TarsUtil.equals(areaCode, other.areaCode) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(name, 0);
		_os.write(areaCode, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.name = _is.readString(0, true);
		this.areaCode = _is.read(areaCode, 1, true);
	}

}
