// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetAreaCodeResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public java.util.List<Province> provinces = null;

	public java.util.List<Province> getProvinces() {
		return provinces;
	}

	public void setProvinces(java.util.List<Province> provinces) {
		this.provinces = provinces;
	}

	public GetAreaCodeResponse() {
	}

	public GetAreaCodeResponse(java.util.List<Province> provinces) {
		this.provinces = provinces;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(provinces);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetAreaCodeResponse)) {
			return false;
		}
		GetAreaCodeResponse other = (GetAreaCodeResponse) obj;
		return (
			TarsUtil.equals(provinces, other.provinces) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(provinces, 0);
	}

	static java.util.List<Province> cache_provinces;
	static { 
		cache_provinces = new java.util.ArrayList<Province>();
		Province var_31 = new Province();
		cache_provinces.add(var_31);
	}

	public void readFrom(TarsInputStream _is) {
		this.provinces = (java.util.List<Province>) _is.read(cache_provinces, 0, true);
	}

}
