// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetAchievementResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public int totalStar = 0;

	public int getTotalStar() {
		return totalStar;
	}

	public void setTotalStar(int totalStar) {
		this.totalStar = totalStar;
	}

	public GetAchievementResponse() {
	}

	public GetAchievementResponse(int totalStar) {
		this.totalStar = totalStar;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(totalStar);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetAchievementResponse)) {
			return false;
		}
		GetAchievementResponse other = (GetAchievementResponse) obj;
		return (
			TarsUtil.equals(totalStar, other.totalStar) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(totalStar, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.totalStar = _is.read(totalStar, 0, true);
	}

}
