// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetBookResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public Book book = null;

	public Book getBook() {
		return book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public GetBookResponse() {
	}

	public GetBookResponse(Book book) {
		this.book = book;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(book);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetBookResponse)) {
			return false;
		}
		GetBookResponse other = (GetBookResponse) obj;
		return (
			TarsUtil.equals(book, other.book) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(book, 0);
	}

	static Book cache_book;
	static { 
		cache_book = new Book();
	}

	public void readFrom(TarsInputStream _is) {
		this.book = (Book) _is.read(cache_book, 0, true);
	}

}
