// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetBannersResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public java.util.List<Banner> banners = null;

	public java.util.List<Banner> getBanners() {
		return banners;
	}

	public void setBanners(java.util.List<Banner> banners) {
		this.banners = banners;
	}

	public GetBannersResponse() {
	}

	public GetBannersResponse(java.util.List<Banner> banners) {
		this.banners = banners;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(banners);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetBannersResponse)) {
			return false;
		}
		GetBannersResponse other = (GetBannersResponse) obj;
		return (
			TarsUtil.equals(banners, other.banners) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(banners, 0);
	}

	static java.util.List<Banner> cache_banners;
	static { 
		cache_banners = new java.util.ArrayList<Banner>();
		Banner var_19 = new Banner();
		cache_banners.add(var_19);
	}

	public void readFrom(TarsInputStream _is) {
		this.banners = (java.util.List<Banner>) _is.read(cache_banners, 0, true);
	}

}
