// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetNotificationsResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public java.util.List<Notification> notifications = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public PageContext pageContext = null;

	public java.util.List<Notification> getNotifications() {
		return notifications;
	}

	public void setNotifications(java.util.List<Notification> notifications) {
		this.notifications = notifications;
	}

	public PageContext getPageContext() {
		return pageContext;
	}

	public void setPageContext(PageContext pageContext) {
		this.pageContext = pageContext;
	}

	public GetNotificationsResponse() {
	}

	public GetNotificationsResponse(java.util.List<Notification> notifications, PageContext pageContext) {
		this.notifications = notifications;
		this.pageContext = pageContext;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(notifications);
		result = prime * result + TarsUtil.hashCode(pageContext);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetNotificationsResponse)) {
			return false;
		}
		GetNotificationsResponse other = (GetNotificationsResponse) obj;
		return (
			TarsUtil.equals(notifications, other.notifications) &&
			TarsUtil.equals(pageContext, other.pageContext) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(notifications, 0);
		if (null != pageContext) {
			_os.write(pageContext, 1);
		}
	}

	static java.util.List<Notification> cache_notifications;
	static { 
		cache_notifications = new java.util.ArrayList<Notification>();
		Notification var_26 = new Notification();
		cache_notifications.add(var_26);
	}
	static PageContext cache_pageContext;
	static { 
		cache_pageContext = new PageContext();
	}

	public void readFrom(TarsInputStream _is) {
		this.notifications = (java.util.List<Notification>) _is.read(cache_notifications, 0, true);
		this.pageContext = (PageContext) _is.read(cache_pageContext, 1, false);
	}

}
