// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetPageRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public int resourceID = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public PageRange pageRange = null;

	public int getResourceID() {
		return resourceID;
	}

	public void setResourceID(int resourceID) {
		this.resourceID = resourceID;
	}

	public PageRange getPageRange() {
		return pageRange;
	}

	public void setPageRange(PageRange pageRange) {
		this.pageRange = pageRange;
	}

	public GetPageRequest() {
	}

	public GetPageRequest(int resourceID, PageRange pageRange) {
		this.resourceID = resourceID;
		this.pageRange = pageRange;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(resourceID);
		result = prime * result + TarsUtil.hashCode(pageRange);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetPageRequest)) {
			return false;
		}
		GetPageRequest other = (GetPageRequest) obj;
		return (
			TarsUtil.equals(resourceID, other.resourceID) &&
			TarsUtil.equals(pageRange, other.pageRange) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(resourceID, 0);
		_os.write(pageRange, 1);
	}

	static PageRange cache_pageRange;
	static { 
		cache_pageRange = new PageRange();
	}

	public void readFrom(TarsInputStream _is) {
		this.resourceID = _is.read(resourceID, 0, true);
		this.pageRange = (PageRange) _is.read(cache_pageRange, 1, true);
	}

}
