// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetPushCountResponse {

	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<PushCount> counts = null;

	public java.util.List<PushCount> getCounts() {
		return counts;
	}

	public void setCounts(java.util.List<PushCount> counts) {
		this.counts = counts;
	}

	public GetPushCountResponse() {
	}

	public GetPushCountResponse(java.util.List<PushCount> counts) {
		this.counts = counts;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(counts);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetPushCountResponse)) {
			return false;
		}
		GetPushCountResponse other = (GetPushCountResponse) obj;
		return (
			TarsUtil.equals(counts, other.counts) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != counts) {
			_os.write(counts, 1);
		}
	}

	static java.util.List<PushCount> cache_counts;
	static { 
		cache_counts = new java.util.ArrayList<PushCount>();
		PushCount var_33 = new PushCount();
		cache_counts.add(var_33);
	}

	public void readFrom(TarsInputStream _is) {
		this.counts = (java.util.List<PushCount>) _is.read(cache_counts, 1, false);
	}

}
