// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetPlayBookResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public java.util.List<PlayBook> playBooks = null;

	public java.util.List<PlayBook> getPlayBooks() {
		return playBooks;
	}

	public void setPlayBooks(java.util.List<PlayBook> playBooks) {
		this.playBooks = playBooks;
	}

	public GetPlayBookResponse() {
	}

	public GetPlayBookResponse(java.util.List<PlayBook> playBooks) {
		this.playBooks = playBooks;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(playBooks);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetPlayBookResponse)) {
			return false;
		}
		GetPlayBookResponse other = (GetPlayBookResponse) obj;
		return (
			TarsUtil.equals(playBooks, other.playBooks) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(playBooks, 0);
	}

	static java.util.List<PlayBook> cache_playBooks;
	static { 
		cache_playBooks = new java.util.ArrayList<PlayBook>();
		PlayBook var_22 = new PlayBook();
		cache_playBooks.add(var_22);
	}

	public void readFrom(TarsInputStream _is) {
		this.playBooks = (java.util.List<PlayBook>) _is.read(cache_playBooks, 0, true);
	}

}
