// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetSecKeyRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public int resourceID = 0;

	public int getResourceID() {
		return resourceID;
	}

	public void setResourceID(int resourceID) {
		this.resourceID = resourceID;
	}

	public GetSecKeyRequest() {
	}

	public GetSecKeyRequest(int resourceID) {
		this.resourceID = resourceID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(resourceID);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetSecKeyRequest)) {
			return false;
		}
		GetSecKeyRequest other = (GetSecKeyRequest) obj;
		return (
			TarsUtil.equals(resourceID, other.resourceID) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(resourceID, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.resourceID = _is.read(resourceID, 0, true);
	}

}
