// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetSchoolsRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public int areaCode = 0;

	public int getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(int areaCode) {
		this.areaCode = areaCode;
	}

	public GetSchoolsRequest() {
	}

	public GetSchoolsRequest(int areaCode) {
		this.areaCode = areaCode;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(areaCode);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetSchoolsRequest)) {
			return false;
		}
		GetSchoolsRequest other = (GetSchoolsRequest) obj;
		return (
			TarsUtil.equals(areaCode, other.areaCode) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(areaCode, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.areaCode = _is.read(areaCode, 0, true);
	}

}
