// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetSecKeyResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public SecKeyPair pair = null;

	public SecKeyPair getPair() {
		return pair;
	}

	public void setPair(SecKeyPair pair) {
		this.pair = pair;
	}

	public GetSecKeyResponse() {
	}

	public GetSecKeyResponse(SecKeyPair pair) {
		this.pair = pair;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(pair);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetSecKeyResponse)) {
			return false;
		}
		GetSecKeyResponse other = (GetSecKeyResponse) obj;
		return (
			TarsUtil.equals(pair, other.pair) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(pair, 0);
	}

	static SecKeyPair cache_pair;
	static { 
		cache_pair = new SecKeyPair();
	}

	public void readFrom(TarsInputStream _is) {
		this.pair = (SecKeyPair) _is.read(cache_pair, 0, true);
	}

}
