// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetUnitsResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public java.util.List<Unit> units = null;

	public java.util.List<Unit> getUnits() {
		return units;
	}

	public void setUnits(java.util.List<Unit> units) {
		this.units = units;
	}

	public GetUnitsResponse() {
	}

	public GetUnitsResponse(java.util.List<Unit> units) {
		this.units = units;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(units);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetUnitsResponse)) {
			return false;
		}
		GetUnitsResponse other = (GetUnitsResponse) obj;
		return (
			TarsUtil.equals(units, other.units) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(units, 0);
	}

	static java.util.List<Unit> cache_units;
	static { 
		cache_units = new java.util.ArrayList<Unit>();
		Unit var_17 = new Unit();
		cache_units.add(var_17);
	}

	public void readFrom(TarsInputStream _is) {
		this.units = (java.util.List<Unit>) _is.read(cache_units, 0, true);
	}

}
