// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetVerifyCodeRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public String mobilePhone = "";

	public String getMobilePhone() {
		return mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public GetVerifyCodeRequest() {
	}

	public GetVerifyCodeRequest(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(mobilePhone);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetVerifyCodeRequest)) {
			return false;
		}
		GetVerifyCodeRequest other = (GetVerifyCodeRequest) obj;
		return (
			TarsUtil.equals(mobilePhone, other.mobilePhone) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(mobilePhone, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.mobilePhone = _is.readString(0, true);
	}

}
