// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class LoginRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public String username = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String password = "";

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public LoginRequest() {
	}

	public LoginRequest(String username, String password) {
		this.username = username;
		this.password = password;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(username);
		result = prime * result + TarsUtil.hashCode(password);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof LoginRequest)) {
			return false;
		}
		LoginRequest other = (LoginRequest) obj;
		return (
			TarsUtil.equals(username, other.username) &&
			TarsUtil.equals(password, other.password) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(username, 0);
		_os.write(password, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.username = _is.readString(0, true);
		this.password = _is.readString(1, true);
	}

}
