// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Mission {

	@TarsStructProperty(order = 0, isRequire = true)
	public int missionID = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public String title = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public int otainedStar = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public int totalStar = 0;
	@TarsStructProperty(order = 4, isRequire = true)
	public java.util.List<MissionItem> words = null;

	public int getMissionID() {
		return missionID;
	}

	public void setMissionID(int missionID) {
		this.missionID = missionID;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getOtainedStar() {
		return otainedStar;
	}

	public void setOtainedStar(int otainedStar) {
		this.otainedStar = otainedStar;
	}

	public int getTotalStar() {
		return totalStar;
	}

	public void setTotalStar(int totalStar) {
		this.totalStar = totalStar;
	}

	public java.util.List<MissionItem> getWords() {
		return words;
	}

	public void setWords(java.util.List<MissionItem> words) {
		this.words = words;
	}

	public Mission() {
	}

	public Mission(int missionID, String title, int otainedStar, int totalStar, java.util.List<MissionItem> words) {
		this.missionID = missionID;
		this.title = title;
		this.otainedStar = otainedStar;
		this.totalStar = totalStar;
		this.words = words;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(missionID);
		result = prime * result + TarsUtil.hashCode(title);
		result = prime * result + TarsUtil.hashCode(otainedStar);
		result = prime * result + TarsUtil.hashCode(totalStar);
		result = prime * result + TarsUtil.hashCode(words);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Mission)) {
			return false;
		}
		Mission other = (Mission) obj;
		return (
			TarsUtil.equals(missionID, other.missionID) &&
			TarsUtil.equals(title, other.title) &&
			TarsUtil.equals(otainedStar, other.otainedStar) &&
			TarsUtil.equals(totalStar, other.totalStar) &&
			TarsUtil.equals(words, other.words) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(missionID, 0);
		_os.write(title, 1);
		_os.write(otainedStar, 2);
		_os.write(totalStar, 3);
		_os.write(words, 4);
	}

	static java.util.List<MissionItem> cache_words;
	static { 
		cache_words = new java.util.ArrayList<MissionItem>();
		MissionItem var_11 = new MissionItem();
		cache_words.add(var_11);
	}

	public void readFrom(TarsInputStream _is) {
		this.missionID = _is.read(missionID, 0, true);
		this.title = _is.readString(1, true);
		this.otainedStar = _is.read(otainedStar, 2, true);
		this.totalStar = _is.read(totalStar, 3, true);
		this.words = (java.util.List<MissionItem>) _is.read(cache_words, 4, true);
	}

}
