// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Module {

	@TarsStructProperty(order = 0, isRequire = true)
	public long moduleID = 0L;
	@TarsStructProperty(order = 1, isRequire = true)
	public String title = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public String name = "";
	@TarsStructProperty(order = 3, isRequire = true)
	public java.util.List<Unit> units = null;
	@TarsStructProperty(order = 4, isRequire = true)
	public PageRange pageRange = null;

	public long getModuleID() {
		return moduleID;
	}

	public void setModuleID(long moduleID) {
		this.moduleID = moduleID;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public java.util.List<Unit> getUnits() {
		return units;
	}

	public void setUnits(java.util.List<Unit> units) {
		this.units = units;
	}

	public PageRange getPageRange() {
		return pageRange;
	}

	public void setPageRange(PageRange pageRange) {
		this.pageRange = pageRange;
	}

	public Module() {
	}

	public Module(long moduleID, String title, String name, java.util.List<Unit> units, PageRange pageRange) {
		this.moduleID = moduleID;
		this.title = title;
		this.name = name;
		this.units = units;
		this.pageRange = pageRange;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(moduleID);
		result = prime * result + TarsUtil.hashCode(title);
		result = prime * result + TarsUtil.hashCode(name);
		result = prime * result + TarsUtil.hashCode(units);
		result = prime * result + TarsUtil.hashCode(pageRange);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Module)) {
			return false;
		}
		Module other = (Module) obj;
		return (
			TarsUtil.equals(moduleID, other.moduleID) &&
			TarsUtil.equals(title, other.title) &&
			TarsUtil.equals(name, other.name) &&
			TarsUtil.equals(units, other.units) &&
			TarsUtil.equals(pageRange, other.pageRange) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(moduleID, 0);
		_os.write(title, 1);
		_os.write(name, 2);
		_os.write(units, 3);
		_os.write(pageRange, 4);
	}

	static java.util.List<Unit> cache_units;
	static { 
		cache_units = new java.util.ArrayList<Unit>();
		Unit var_6 = new Unit();
		cache_units.add(var_6);
	}
	static PageRange cache_pageRange;
	static { 
		cache_pageRange = new PageRange();
	}

	public void readFrom(TarsInputStream _is) {
		this.moduleID = _is.read(moduleID, 0, true);
		this.title = _is.readString(1, true);
		this.name = _is.readString(2, true);
		this.units = (java.util.List<Unit>) _is.read(cache_units, 3, true);
		this.pageRange = (PageRange) _is.read(cache_pageRange, 4, true);
	}

}
