// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Notification {

	@TarsStructProperty(order = 0, isRequire = true)
	public int notificationId = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public String title = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public String content = "";
	@TarsStructProperty(order = 3, isRequire = true)
	public long createTime = 0L;
	@TarsStructProperty(order = 4, isRequire = false)
	public String jumpURL = "";

	public int getNotificationId() {
		return notificationId;
	}

	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public long getCreateTime() {
		return createTime;
	}

	public void setCreateTime(long createTime) {
		this.createTime = createTime;
	}

	public String getJumpURL() {
		return jumpURL;
	}

	public void setJumpURL(String jumpURL) {
		this.jumpURL = jumpURL;
	}

	public Notification() {
	}

	public Notification(int notificationId, String title, String content, long createTime, String jumpURL) {
		this.notificationId = notificationId;
		this.title = title;
		this.content = content;
		this.createTime = createTime;
		this.jumpURL = jumpURL;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(notificationId);
		result = prime * result + TarsUtil.hashCode(title);
		result = prime * result + TarsUtil.hashCode(content);
		result = prime * result + TarsUtil.hashCode(createTime);
		result = prime * result + TarsUtil.hashCode(jumpURL);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Notification)) {
			return false;
		}
		Notification other = (Notification) obj;
		return (
			TarsUtil.equals(notificationId, other.notificationId) &&
			TarsUtil.equals(title, other.title) &&
			TarsUtil.equals(content, other.content) &&
			TarsUtil.equals(createTime, other.createTime) &&
			TarsUtil.equals(jumpURL, other.jumpURL) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(notificationId, 0);
		_os.write(title, 1);
		_os.write(content, 2);
		_os.write(createTime, 3);
		if (null != jumpURL) {
			_os.write(jumpURL, 4);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.notificationId = _is.read(notificationId, 0, true);
		this.title = _is.readString(1, true);
		this.content = _is.readString(2, true);
		this.createTime = _is.read(createTime, 3, true);
		this.jumpURL = _is.readString(4, false);
	}

}
