// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class PageRange {

	@TarsStructProperty(order = 0, isRequire = true)
	public int start = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public int end = 0;

	public int getStart() {
		return start;
	}

	public void setStart(int start) {
		this.start = start;
	}

	public int getEnd() {
		return end;
	}

	public void setEnd(int end) {
		this.end = end;
	}

	public PageRange() {
	}

	public PageRange(int start, int end) {
		this.start = start;
		this.end = end;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(start);
		result = prime * result + TarsUtil.hashCode(end);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof PageRange)) {
			return false;
		}
		PageRange other = (PageRange) obj;
		return (
			TarsUtil.equals(start, other.start) &&
			TarsUtil.equals(end, other.end) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(start, 0);
		_os.write(end, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.start = _is.read(start, 0, true);
		this.end = _is.read(end, 1, true);
	}

}
