// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class PageContext {

	@TarsStructProperty(order = 0, isRequire = false)
	public int context = 0;

	public int getContext() {
		return context;
	}

	public void setContext(int context) {
		this.context = context;
	}

	public PageContext() {
	}

	public PageContext(int context) {
		this.context = context;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(context);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof PageContext)) {
			return false;
		}
		PageContext other = (PageContext) obj;
		return (
			TarsUtil.equals(context, other.context) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(context, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.context = _is.read(context, 0, false);
	}

}
