// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Part {

	@TarsStructProperty(order = 0, isRequire = true)
	public String title = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public java.util.List<Mission> missions = null;

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public java.util.List<Mission> getMissions() {
		return missions;
	}

	public void setMissions(java.util.List<Mission> missions) {
		this.missions = missions;
	}

	public Part() {
	}

	public Part(String title, java.util.List<Mission> missions) {
		this.title = title;
		this.missions = missions;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(title);
		result = prime * result + TarsUtil.hashCode(missions);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Part)) {
			return false;
		}
		Part other = (Part) obj;
		return (
			TarsUtil.equals(title, other.title) &&
			TarsUtil.equals(missions, other.missions) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(title, 0);
		_os.write(missions, 1);
	}

	static java.util.List<Mission> cache_missions;
	static { 
		cache_missions = new java.util.ArrayList<Mission>();
		Mission var_12 = new Mission();
		cache_missions.add(var_12);
	}

	public void readFrom(TarsInputStream _is) {
		this.title = _is.readString(0, true);
		this.missions = (java.util.List<Mission>) _is.read(cache_missions, 1, true);
	}

}
