// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class PlayBook {

	@TarsStructProperty(order = 0, isRequire = true)
	public String title = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String coverURL = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public java.util.List<String> roles = null;
	@TarsStructProperty(order = 3, isRequire = true)
	public java.util.List<Dialogue> lines = null;

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCoverURL() {
		return coverURL;
	}

	public void setCoverURL(String coverURL) {
		this.coverURL = coverURL;
	}

	public java.util.List<String> getRoles() {
		return roles;
	}

	public void setRoles(java.util.List<String> roles) {
		this.roles = roles;
	}

	public java.util.List<Dialogue> getLines() {
		return lines;
	}

	public void setLines(java.util.List<Dialogue> lines) {
		this.lines = lines;
	}

	public PlayBook() {
	}

	public PlayBook(String title, String coverURL, java.util.List<String> roles, java.util.List<Dialogue> lines) {
		this.title = title;
		this.coverURL = coverURL;
		this.roles = roles;
		this.lines = lines;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(title);
		result = prime * result + TarsUtil.hashCode(coverURL);
		result = prime * result + TarsUtil.hashCode(roles);
		result = prime * result + TarsUtil.hashCode(lines);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof PlayBook)) {
			return false;
		}
		PlayBook other = (PlayBook) obj;
		return (
			TarsUtil.equals(title, other.title) &&
			TarsUtil.equals(coverURL, other.coverURL) &&
			TarsUtil.equals(roles, other.roles) &&
			TarsUtil.equals(lines, other.lines) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(title, 0);
		_os.write(coverURL, 1);
		_os.write(roles, 2);
		_os.write(lines, 3);
	}

	static java.util.List<String> cache_roles;
	static { 
		cache_roles = new java.util.ArrayList<String>();
		String var_9 = "";
		cache_roles.add(var_9);
	}
	static java.util.List<Dialogue> cache_lines;
	static { 
		cache_lines = new java.util.ArrayList<Dialogue>();
		Dialogue var_10 = new Dialogue();
		cache_lines.add(var_10);
	}

	public void readFrom(TarsInputStream _is) {
		this.title = _is.readString(0, true);
		this.coverURL = _is.readString(1, true);
		this.roles = (java.util.List<String>) _is.read(cache_roles, 2, true);
		this.lines = (java.util.List<Dialogue>) _is.read(cache_lines, 3, true);
	}

}
