// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class PostReadAfterMeScoreRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public long bookID = 0L;
	@TarsStructProperty(order = 1, isRequire = true)
	public Score result = null;

	public long getBookID() {
		return bookID;
	}

	public void setBookID(long bookID) {
		this.bookID = bookID;
	}

	public Score getResult() {
		return result;
	}

	public void setResult(Score result) {
		this.result = result;
	}

	public PostReadAfterMeScoreRequest() {
	}

	public PostReadAfterMeScoreRequest(long bookID, Score result) {
		this.bookID = bookID;
		this.result = result;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(bookID);
		result = prime * result + TarsUtil.hashCode(result);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof PostReadAfterMeScoreRequest)) {
			return false;
		}
		PostReadAfterMeScoreRequest other = (PostReadAfterMeScoreRequest) obj;
		return (
			TarsUtil.equals(bookID, other.bookID) &&
			TarsUtil.equals(result, other.result) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(bookID, 0);
		_os.write(result, 1);
	}

	static Score cache_result;
	static { 
		cache_result = new Score();
	}

	public void readFrom(TarsInputStream _is) {
		this.bookID = _is.read(bookID, 0, true);
		this.result = (Score) _is.read(cache_result, 1, true);
	}

}
