// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class ProfileRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public long userId = 0L;

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public ProfileRequest() {
	}

	public ProfileRequest(long userId) {
		this.userId = userId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(userId);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof ProfileRequest)) {
			return false;
		}
		ProfileRequest other = (ProfileRequest) obj;
		return (
			TarsUtil.equals(userId, other.userId) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(userId, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.userId = _is.read(userId, 0, true);
	}

}
