// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class QA {

	@TarsStructProperty(order = 0, isRequire = true)
	public String title = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String content = "";

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public QA() {
	}

	public QA(String title, String content) {
		this.title = title;
		this.content = content;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(title);
		result = prime * result + TarsUtil.hashCode(content);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof QA)) {
			return false;
		}
		QA other = (QA) obj;
		return (
			TarsUtil.equals(title, other.title) &&
			TarsUtil.equals(content, other.content) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(title, 0);
		_os.write(content, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.title = _is.readString(0, true);
		this.content = _is.readString(1, true);
	}

}
