// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class ReadNotificationRequest {

	@TarsStructProperty(order = 0, isRequire = false)
	public int notificationId = 0;

	public int getNotificationId() {
		return notificationId;
	}

	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}

	public ReadNotificationRequest() {
	}

	public ReadNotificationRequest(int notificationId) {
		this.notificationId = notificationId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(notificationId);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof ReadNotificationRequest)) {
			return false;
		}
		ReadNotificationRequest other = (ReadNotificationRequest) obj;
		return (
			TarsUtil.equals(notificationId, other.notificationId) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(notificationId, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.notificationId = _is.read(notificationId, 0, false);
	}

}
