// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Score {

	@TarsStructProperty(order = 0, isRequire = true)
	public int missionID = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public int score = 0;

	public int getMissionID() {
		return missionID;
	}

	public void setMissionID(int missionID) {
		this.missionID = missionID;
	}

	public int getScore() {
		return score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public Score() {
	}

	public Score(int missionID, int score) {
		this.missionID = missionID;
		this.score = score;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(missionID);
		result = prime * result + TarsUtil.hashCode(score);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Score)) {
			return false;
		}
		Score other = (Score) obj;
		return (
			TarsUtil.equals(missionID, other.missionID) &&
			TarsUtil.equals(score, other.score) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(missionID, 0);
		_os.write(score, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.missionID = _is.read(missionID, 0, true);
		this.score = _is.read(score, 1, true);
	}

}
