// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class SendFeedbackRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public String content = "";

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public SendFeedbackRequest() {
	}

	public SendFeedbackRequest(String content) {
		this.content = content;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(content);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof SendFeedbackRequest)) {
			return false;
		}
		SendFeedbackRequest other = (SendFeedbackRequest) obj;
		return (
			TarsUtil.equals(content, other.content) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(content, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.content = _is.readString(0, true);
	}

}
