// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Size {

	@TarsStructProperty(order = 0, isRequire = true)
	public String width = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String height = "";

	public String getWidth() {
		return width;
	}

	public void setWidth(String width) {
		this.width = width;
	}

	public String getHeight() {
		return height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public Size() {
	}

	public Size(String width, String height) {
		this.width = width;
		this.height = height;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(width);
		result = prime * result + TarsUtil.hashCode(height);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Size)) {
			return false;
		}
		Size other = (Size) obj;
		return (
			TarsUtil.equals(width, other.width) &&
			TarsUtil.equals(height, other.height) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(width, 0);
		_os.write(height, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.width = _is.readString(0, true);
		this.height = _is.readString(1, true);
	}

}
