// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Unit {

	@TarsStructProperty(order = 0, isRequire = true)
	public long unitID = 0L;
	@TarsStructProperty(order = 1, isRequire = true)
	public String title = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public String name = "";
	@TarsStructProperty(order = 3, isRequire = true)
	public String coverURL = "";
	@TarsStructProperty(order = 4, isRequire = true)
	public int canRolePlay = 0;
	@TarsStructProperty(order = 5, isRequire = true)
	public PageRange pageRange = null;

	public long getUnitID() {
		return unitID;
	}

	public void setUnitID(long unitID) {
		this.unitID = unitID;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCoverURL() {
		return coverURL;
	}

	public void setCoverURL(String coverURL) {
		this.coverURL = coverURL;
	}

	public int getCanRolePlay() {
		return canRolePlay;
	}

	public void setCanRolePlay(int canRolePlay) {
		this.canRolePlay = canRolePlay;
	}

	public PageRange getPageRange() {
		return pageRange;
	}

	public void setPageRange(PageRange pageRange) {
		this.pageRange = pageRange;
	}

	public Unit() {
	}

	public Unit(long unitID, String title, String name, String coverURL, int canRolePlay, PageRange pageRange) {
		this.unitID = unitID;
		this.title = title;
		this.name = name;
		this.coverURL = coverURL;
		this.canRolePlay = canRolePlay;
		this.pageRange = pageRange;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(unitID);
		result = prime * result + TarsUtil.hashCode(title);
		result = prime * result + TarsUtil.hashCode(name);
		result = prime * result + TarsUtil.hashCode(coverURL);
		result = prime * result + TarsUtil.hashCode(canRolePlay);
		result = prime * result + TarsUtil.hashCode(pageRange);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Unit)) {
			return false;
		}
		Unit other = (Unit) obj;
		return (
			TarsUtil.equals(unitID, other.unitID) &&
			TarsUtil.equals(title, other.title) &&
			TarsUtil.equals(name, other.name) &&
			TarsUtil.equals(coverURL, other.coverURL) &&
			TarsUtil.equals(canRolePlay, other.canRolePlay) &&
			TarsUtil.equals(pageRange, other.pageRange) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(unitID, 0);
		_os.write(title, 1);
		_os.write(name, 2);
		_os.write(coverURL, 3);
		_os.write(canRolePlay, 4);
		_os.write(pageRange, 5);
	}

	static PageRange cache_pageRange;
	static { 
		cache_pageRange = new PageRange();
	}

	public void readFrom(TarsInputStream _is) {
		this.unitID = _is.read(unitID, 0, true);
		this.title = _is.readString(1, true);
		this.name = _is.readString(2, true);
		this.coverURL = _is.readString(3, true);
		this.canRolePlay = _is.read(canRolePlay, 4, true);
		this.pageRange = (PageRange) _is.read(cache_pageRange, 5, true);
	}

}
