// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class UpdateUserInfoRequest {

	@TarsStructProperty(order = 0, isRequire = false)
	public String name = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String avatar = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public long schoolId = 0L;
	@TarsStructProperty(order = 3, isRequire = false)
	public int areaCode = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public String nameOfClass = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public long bookId = 0L;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public long getSchoolId() {
		return schoolId;
	}

	public void setSchoolId(long schoolId) {
		this.schoolId = schoolId;
	}

	public int getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(int areaCode) {
		this.areaCode = areaCode;
	}

	public String getNameOfClass() {
		return nameOfClass;
	}

	public void setNameOfClass(String nameOfClass) {
		this.nameOfClass = nameOfClass;
	}

	public long getBookId() {
		return bookId;
	}

	public void setBookId(long bookId) {
		this.bookId = bookId;
	}

	public UpdateUserInfoRequest() {
	}

	public UpdateUserInfoRequest(String name, String avatar, long schoolId, int areaCode, String nameOfClass, long bookId) {
		this.name = name;
		this.avatar = avatar;
		this.schoolId = schoolId;
		this.areaCode = areaCode;
		this.nameOfClass = nameOfClass;
		this.bookId = bookId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(name);
		result = prime * result + TarsUtil.hashCode(avatar);
		result = prime * result + TarsUtil.hashCode(schoolId);
		result = prime * result + TarsUtil.hashCode(areaCode);
		result = prime * result + TarsUtil.hashCode(nameOfClass);
		result = prime * result + TarsUtil.hashCode(bookId);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof UpdateUserInfoRequest)) {
			return false;
		}
		UpdateUserInfoRequest other = (UpdateUserInfoRequest) obj;
		return (
			TarsUtil.equals(name, other.name) &&
			TarsUtil.equals(avatar, other.avatar) &&
			TarsUtil.equals(schoolId, other.schoolId) &&
			TarsUtil.equals(areaCode, other.areaCode) &&
			TarsUtil.equals(nameOfClass, other.nameOfClass) &&
			TarsUtil.equals(bookId, other.bookId) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != name) {
			_os.write(name, 0);
		}
		if (null != avatar) {
			_os.write(avatar, 1);
		}
		_os.write(schoolId, 2);
		_os.write(areaCode, 3);
		if (null != nameOfClass) {
			_os.write(nameOfClass, 4);
		}
		_os.write(bookId, 5);
	}


	public void readFrom(TarsInputStream _is) {
		this.name = _is.readString(0, false);
		this.avatar = _is.readString(1, false);
		this.schoolId = _is.read(schoolId, 2, false);
		this.areaCode = _is.read(areaCode, 3, false);
		this.nameOfClass = _is.readString(4, false);
		this.bookId = _is.read(bookId, 5, false);
	}

}
