// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class User {

	@TarsStructProperty(order = 0, isRequire = true)
	public long userId = 0L;
	@TarsStructProperty(order = 1, isRequire = true)
	public String nickname = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public String avatarURL = "";
	@TarsStructProperty(order = 3, isRequire = true)
	public String school = "";
	@TarsStructProperty(order = 4, isRequire = true)
	public String nameOfClass = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public Purchase purchase = null;
	@TarsStructProperty(order = 6, isRequire = false)
	public long usingBook = 0L;
	@TarsStructProperty(order = 7, isRequire = false)
	public String area = "";

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getAvatarURL() {
		return avatarURL;
	}

	public void setAvatarURL(String avatarURL) {
		this.avatarURL = avatarURL;
	}

	public String getSchool() {
		return school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getNameOfClass() {
		return nameOfClass;
	}

	public void setNameOfClass(String nameOfClass) {
		this.nameOfClass = nameOfClass;
	}

	public Purchase getPurchase() {
		return purchase;
	}

	public void setPurchase(Purchase purchase) {
		this.purchase = purchase;
	}

	public long getUsingBook() {
		return usingBook;
	}

	public void setUsingBook(long usingBook) {
		this.usingBook = usingBook;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public User() {
	}

	public User(long userId, String nickname, String avatarURL, String school, String nameOfClass, Purchase purchase, long usingBook, String area) {
		this.userId = userId;
		this.nickname = nickname;
		this.avatarURL = avatarURL;
		this.school = school;
		this.nameOfClass = nameOfClass;
		this.purchase = purchase;
		this.usingBook = usingBook;
		this.area = area;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(userId);
		result = prime * result + TarsUtil.hashCode(nickname);
		result = prime * result + TarsUtil.hashCode(avatarURL);
		result = prime * result + TarsUtil.hashCode(school);
		result = prime * result + TarsUtil.hashCode(nameOfClass);
		result = prime * result + TarsUtil.hashCode(purchase);
		result = prime * result + TarsUtil.hashCode(usingBook);
		result = prime * result + TarsUtil.hashCode(area);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof User)) {
			return false;
		}
		User other = (User) obj;
		return (
			TarsUtil.equals(userId, other.userId) &&
			TarsUtil.equals(nickname, other.nickname) &&
			TarsUtil.equals(avatarURL, other.avatarURL) &&
			TarsUtil.equals(school, other.school) &&
			TarsUtil.equals(nameOfClass, other.nameOfClass) &&
			TarsUtil.equals(purchase, other.purchase) &&
			TarsUtil.equals(usingBook, other.usingBook) &&
			TarsUtil.equals(area, other.area) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(userId, 0);
		_os.write(nickname, 1);
		_os.write(avatarURL, 2);
		_os.write(school, 3);
		_os.write(nameOfClass, 4);
		if (null != purchase) {
			_os.write(purchase, 5);
		}
		_os.write(usingBook, 6);
		if (null != area) {
			_os.write(area, 7);
		}
	}

	static Purchase cache_purchase;
	static { 
		cache_purchase = new Purchase();
	}

	public void readFrom(TarsInputStream _is) {
		this.userId = _is.read(userId, 0, true);
		this.nickname = _is.readString(1, true);
		this.avatarURL = _is.readString(2, true);
		this.school = _is.readString(3, true);
		this.nameOfClass = _is.readString(4, true);
		this.purchase = (Purchase) _is.read(cache_purchase, 5, false);
		this.usingBook = _is.read(usingBook, 6, false);
		this.area = _is.readString(7, false);
	}

}
