// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.king.reading.ddb;

public enum UserFieldType {

	Nickname(0),
	AvatarURL(1),
	School(2),
	GradeName(3),
	ClassName(4),
	UsingBook(5),
	Province(6),
	City(7);

	private final int value;

	private UserFieldType(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static UserFieldType convert(int value) {
		for(UserFieldType v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
